### ISSUE TITLE
A/B Testing

### ISSUE THREAD

**Issue by DavidLemayian** [ziadoz/awesome-php#353]
Any great A/B testing suites anyone can suggest?

**Comment by hacfi** [comment]
@DavidLemayian Have a look at https://github.com/etsy/feature

**Comment by xethorn** [comment]
A lot of their code is [tightly coupled](https://github.com/etsy/feature/blob/master/phpunit/Feature/WorldTest.php#L134) with parts of their codebase which hasn't been made public (even if they have tried to [clean it up](https://github.com/etsy/feature/commit/94ccce8e5ad83edde5bd9bcfb39e8b238de6ac97).) It will take you less time to write your own library instead of using theirs - mostly because your codebase has a [different structure](https://github.com/etsy/feature/blob/master/Feature/World.php#L28) (your user ids might be different than theirs.)

Writing your own library is actually very simple as long as you keep in mind two things: A/B testing has only two concerns.

* The feature variants (for a defined feature, how many variants do you have.)
* The population for each variants and the population selection criteria. 

We've written our own at The Orchard after spending too much time with etsy/feature. I'll try to see if we can open-source it. Our code is a few hundred of lines (including tests.)

**Comment by hacfi** [comment]
@xethorn Thanks for the detailed explanation! I haven’t implemented etsy/feature yet but it’s on my todo list. Would be very interested in your library - if you find the time to open source it please let us know!

**Comment by xethorn** [comment]
Absolutely.

**Comment by DavidLemayian** [comment]
Thank you @hacfi and @xethorn! Finding it weird that there aren't enough really good A/B testing libraries for php.

Can't wait to check out the hundred or so lines of code. :)
